// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/grpcservice/pushmessage.proto

package pushmessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_INFO    MessageType = 0
	MessageType_WARNING MessageType = 1
	MessageType_ERROR   MessageType = 2
	MessageType_SUCCESS MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "ERROR",
		3: "SUCCESS",
	}
	MessageType_value = map[string]int32{
		"INFO":    0,
		"WARNING": 1,
		"ERROR":   2,
		"SUCCESS": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_grpcservice_pushmessage_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_grpcservice_pushmessage_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_grpcservice_pushmessage_proto_rawDescGZIP(), []int{0}
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"` // สามารถระบุ topic ที่ต้องการ subscribe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_grpcservice_pushmessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcservice_pushmessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcservice_pushmessage_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PushRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Type          MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=pushmessage.MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_proto_grpcservice_pushmessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcservice_pushmessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_proto_grpcservice_pushmessage_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PushMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PushMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PushMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_INFO
}

var File_proto_grpcservice_pushmessage_proto protoreflect.FileDescriptor

const file_proto_grpcservice_pushmessage_proto_rawDesc = "" +
	"\n" +
	"#proto/grpcservice/pushmessage.proto\x12\vpushmessage\"@\n" +
	"\vPushRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x99\x01\n" +
	"\vPushMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12,\n" +
	"\x04type\x18\x05 \x01(\x0e2\x18.pushmessage.MessageTypeR\x04type*<\n" +
	"\vMessageType\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x032c\n" +
	"\x12PushMessageService\x12M\n" +
	"\x15SubscribePushMessages\x12\x18.pushmessage.PushRequest\x1a\x18.pushmessage.PushMessage0\x01B0Z.internal/grpcservice/protogenerate/pushmessageb\x06proto3"

var (
	file_proto_grpcservice_pushmessage_proto_rawDescOnce sync.Once
	file_proto_grpcservice_pushmessage_proto_rawDescData []byte
)

func file_proto_grpcservice_pushmessage_proto_rawDescGZIP() []byte {
	file_proto_grpcservice_pushmessage_proto_rawDescOnce.Do(func() {
		file_proto_grpcservice_pushmessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpcservice_pushmessage_proto_rawDesc), len(file_proto_grpcservice_pushmessage_proto_rawDesc)))
	})
	return file_proto_grpcservice_pushmessage_proto_rawDescData
}

var file_proto_grpcservice_pushmessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_grpcservice_pushmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grpcservice_pushmessage_proto_goTypes = []any{
	(MessageType)(0),    // 0: pushmessage.MessageType
	(*PushRequest)(nil), // 1: pushmessage.PushRequest
	(*PushMessage)(nil), // 2: pushmessage.PushMessage
}
var file_proto_grpcservice_pushmessage_proto_depIdxs = []int32{
	0, // 0: pushmessage.PushMessage.type:type_name -> pushmessage.MessageType
	1, // 1: pushmessage.PushMessageService.SubscribePushMessages:input_type -> pushmessage.PushRequest
	2, // 2: pushmessage.PushMessageService.SubscribePushMessages:output_type -> pushmessage.PushMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_grpcservice_pushmessage_proto_init() }
func file_proto_grpcservice_pushmessage_proto_init() {
	if File_proto_grpcservice_pushmessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpcservice_pushmessage_proto_rawDesc), len(file_proto_grpcservice_pushmessage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcservice_pushmessage_proto_goTypes,
		DependencyIndexes: file_proto_grpcservice_pushmessage_proto_depIdxs,
		EnumInfos:         file_proto_grpcservice_pushmessage_proto_enumTypes,
		MessageInfos:      file_proto_grpcservice_pushmessage_proto_msgTypes,
	}.Build()
	File_proto_grpcservice_pushmessage_proto = out.File
	file_proto_grpcservice_pushmessage_proto_goTypes = nil
	file_proto_grpcservice_pushmessage_proto_depIdxs = nil
}
